In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import pandas as pd
import time
import os

In [2]:
driver = webdriver.Chrome("C:\Sid folder\Studies\Sem 6\Web Mining\DA Project\chromedriverold.exe")

driver.get('https://in.indeed.com/jobs?q=&l=India')
driver.maximize_window()

<ipython-input-2-1d88528fe2b8>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("C:\Sid folder\Studies\Sem 6\Web Mining\DA Project\chromedriverold.exe")

In [3]:
job_title = []
company_name = []
location = []
job_link = []
emp_type = []
no_of_jobs = 5000

In [4]:
x = 2
temp = []
while x <= int(no_of_jobs/15)+1: 
    x = x+1
    try:
        driver.find_element(By.XPATH, "/html/body/main/div/div[1]/div/div/div[5]/div[1]/nav/div[last()]/a").click()
        time.sleep(2)
        jobs = []
        try:
            job_list = driver.find_element(By.ID, "mosaic-jobResults")
        except:
            job_list = driver.find_element(By.ID, "mosaic-jobcards")
        for i in job_list.find_elements(By.CSS_SELECTOR, ".jobsearch-ResultsList > li"):
            jobs.append(i)
        
        for job in jobs:
            try:
                temptype = job.find_elements(By.CLASS_NAME, "attribute_snippet")[1].get_attribute("innerText")
            except:
                temptype = "None"
            try:
                temptitle = job.find_element(By.TAG_NAME, "h2").get_attribute("innerText")
                tempname = job.find_element(By.CLASS_NAME, "companyName").get_attribute("innerText")
                temploc = job.find_element(By.CLASS_NAME, "companyLocation").get_attribute("innerText")
                templink = job.find_element(By.CLASS_NAME, "jcs-JobTitle").get_attribute("href")

                job_title.append(temptitle)
                company_name.append(tempname)
                location.append(temploc)
                job_link.append(templink)
                emp_type.append(temptype)

            except:
                continue
    except:
        continue

In [5]:
print(len(job_title))

1444

In [6]:
for i in range(10):
    print(job_title[i], company_name[i], location[i], emp_type[i], sep = "\n")
    print()

driver.close()

Teaching Faculty
SONAM TUITIONS
Kalyan, Maharashtra
Flexible shift

Norwegian content writer required
Great Ponton
Mumbai, Maharashtra
Day shift

MBA (Marketing)
Astrotel Pvt Ltd
Kanpur, Uttar Pradesh
Full-time

Visa counsellor
VISA SPOT
Mohali, Punjab
Full-time

Scrum Master 4
Comcast
Chennai, Tamil Nadu
Weekend availability

Wanted Teachers For MBA
RAM DEVI JINDAL EDUCATIONAL CHARITABLE SOCIETY...
Mohali, Punjab
Full-time

NHS Diagnostic Radiographer â€“ Relocate to the UK
NHS Professionals
Chennai, Tamil Nadu
Regular / Permanent
+1

PGT Biology Teacher
Recruitment Wing Consultants
Jamshedpur, Jharkhand
Regular / Permanent
+1

Permanent Work from home
Suvision holding Pvt limited
Remote in Anantapur, Andhra Pradesh
Regular / Permanent
+1

Receptionist/Administration
SHRI SHARDA GROUP
Jaunpur, Uttar Pradesh
Full-time

In [7]:
filename = "db.csv"

if not os.path.exists(filename):
    with open(filename, "w"):
        print(f"{filename} has been created.")
else:
    print(f"{filename} already exists.")

db.csv already exists.

In [8]:
job_data = pd.DataFrame({
    "Title": job_title,
    "Company": company_name,
    "Location": location,
    "Type": emp_type,
    "Link": job_link
})

display(job_data)

job_data.to_csv("db.csv", mode = 'a', index = False, header = False)

,Title,Company,Location,Type,Link
0,Teaching Faculty,SONAM TUITIONS,"Kalyan, Maharashtra",Flexible shift,https://in.indeed.com/pagead/clk?mo=r&ad=-6NYl...
1,Norwegian content writer required,Great Ponton,"Mumbai, Maharashtra",Day shift,https://in.indeed.com/pagead/clk?mo=r&ad=-6NYl...
2,MBA (Marketing),Astrotel Pvt Ltd,"Kanpur, Uttar Pradesh",Full-time,https://in.indeed.com/pagead/clk?mo=r&ad=-6NYl...
3,Visa counsellor,VISA SPOT,"Mohali, Punjab",Full-time,https://in.indeed.com/pagead/clk?mo=r&ad=-6NYl...
4,Scrum Master 4,Comcast,"Chennai, Tamil Nadu",Weekend availability,https://in.indeed.com/pagead/clk?mo=r&ad=-6NYl...
...,...,...,...,...,...
1439,Front Desk Executive,DermaClinix,"Krishna Market, Delhi",None,https://in.indeed.com/rc/clk?jk=53ffb35aff3731...
1440,Us Sales Tele Calling (Night Shift) Work from ...,99yrs Network LLP,"Remote in Mumbai, Maharashtra",Full-time,https://in.indeed.com/company/99yrs-Network-LL...
1441,Personal Secretary,Benaka Gold Company,"Bengaluru, Karnataka",Regular / Permanent\n+2,https://in.indeed.com/company/BENAKA-GOLD-COMP...
1442,AMC sales executive,Numeric Power Systems Limited,"Lucknow, Uttar Pradesh\n+2 locations",Full-time,https://in.indeed.com/company/Numeric-Power-Sy...
1443,Copywriter,HIRINGNINJA,"Gurgaon, Haryana",Regular / Permanent\n+1,https://in.indeed.com/company/HiringNinja/jobs...